### ISSUE TITLE
1.8 not compatible, despite Wiki saying it is

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1559]
Spigot version 1.8 (git-Spigot-550ebac-7019900), Denizen_Developmental build 139, and Depenizen build 380. Despite saying that the latest Denizen and Depenizen works with 1.8+, it does not work on 1.8. It returns an error and incompatibility message.

```
[20:02:26] [Server thread/INFO]: [Denizen] Enabling Denizen v1.0.1-SNAPSHOT (build 139)
[20:02:26] [Server thread/WARN]: [Denizen] -------------------------------------
[20:02:26] [Server thread/WARN]: [Denizen] Denizen is not compatible with this Spigot version! Deactivating Denizen!
[20:02:26] [Server thread/WARN]: [Denizen] -------------------------------------
[20:02:26] [Server thread/INFO]: [Denizen] Disabling Denizen v1.0.1-SNAPSHOT (build 139)
[20:02:26] [Server thread/INFO]: [Depenizen] Enabling Depenizen v1.0.0 (build 380)
[20:02:26] [Server thread/ERROR]: Error occurred while enabling Depenizen v1.0.0 (build 380) (Is it up to date?)
java.lang.NoClassDefFoundError: net/aufdemrand/denizen/utilities/debugging/dB
	at com.denizenscript.depenizen.bukkit.DepenizenPlugin.depenizenLog(DepenizenPlugin.java:69) ~[?:?]
	at com.denizenscript.depenizen.bukkit.DepenizenPlugin.checkPlugins(DepenizenPlugin.java:57) ~[?:?]
	at com.denizenscript.depenizen.bukkit.DepenizenPlugin.onEnable(DepenizenPlugin.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizen.utilities.debugging.dB
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 14 more
```

**Comment by mcmonkey4eva** [comment]
Denizen is compatible with 1.8.8 final - not 1.8 R1 pre-release...

**Comment by MusicScore** [comment]
Ah. Thank you for the clarification.
